income = input("Enter your monthly income:")
expenses = input("Enter your total monthly expenses:")
monthly_savings = int(income) - int(expenses)
annual_savings = monthly_savings * 12 + (monthly_savings * 12 * 0.05)
print("Your monthly savings are", monthly_savings,".")
print("Projected savings after one year, with interest, is:", int(annual_savings),".")
